// Code generated by MockGen. DO NOT EDIT.
// Source: clients.go
//
// Generated by this command:
//
//	mockgen -destination=./clients_mock_test.go -package=request -source=clients.go BillingClient,LLMClient,ChatClient
//

// Package request is a generated GoMock package.
package request

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingClient is a mock of BillingClient interface.
type MockBillingClient struct {
	ctrl     *gomock.Controller
	recorder *MockBillingClientMockRecorder
	isgomock struct{}
}

// MockBillingClientMockRecorder is the mock recorder for MockBillingClient.
type MockBillingClientMockRecorder struct {
	mock *MockBillingClient
}

// NewMockBillingClient creates a new mock instance.
func NewMockBillingClient(ctrl *gomock.Controller) *MockBillingClient {
	mock := &MockBillingClient{ctrl: ctrl}
	mock.recorder = &MockBillingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingClient) EXPECT() *MockBillingClientMockRecorder {
	return m.recorder
}

// DebitToken mocks base method.
func (m *MockBillingClient) DebitToken(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebitToken", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DebitToken indicates an expected call of DebitToken.
func (mr *MockBillingClientMockRecorder) DebitToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebitToken", reflect.TypeOf((*MockBillingClient)(nil).DebitToken), ctx, userID)
}

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockLLMClient) Summarize(ctx context.Context, twilioSID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, twilioSID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockLLMClientMockRecorder) Summarize(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockLLMClient)(nil).Summarize), ctx, twilioSID)
}

// MockChatClient is a mock of ChatClient interface.
type MockChatClient struct {
	ctrl     *gomock.Controller
	recorder *MockChatClientMockRecorder
	isgomock struct{}
}

// MockChatClientMockRecorder is the mock recorder for MockChatClient.
type MockChatClientMockRecorder struct {
	mock *MockChatClient
}

// NewMockChatClient creates a new mock instance.
func NewMockChatClient(ctrl *gomock.Controller) *MockChatClient {
	mock := &MockChatClient{ctrl: ctrl}
	mock.recorder = &MockChatClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatClient) EXPECT() *MockChatClientMockRecorder {
	return m.recorder
}

// AddExpert mocks base method.
func (m *MockChatClient) AddExpert(ctx context.Context, twilioSID string, expertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExpert", ctx, twilioSID, expertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExpert indicates an expected call of AddExpert.
func (mr *MockChatClientMockRecorder) AddExpert(ctx, twilioSID, expertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExpert", reflect.TypeOf((*MockChatClient)(nil).AddExpert), ctx, twilioSID, expertID)
}

// RemoveBot mocks base method.
func (m *MockChatClient) RemoveBot(ctx context.Context, twilioSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBot", ctx, twilioSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBot indicates an expected call of RemoveBot.
func (mr *MockChatClientMockRecorder) RemoveBot(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBot", reflect.TypeOf((*MockChatClient)(nil).RemoveBot), ctx, twilioSID)
}
