// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -destination=./repository_mock_test.go -package=request -source=repository.go Repository
//

// Package request is a generated GoMock package.
package request

import (
	context "context"
	domain "project-sage/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AcceptRequest mocks base method.
func (m *MockRepository) AcceptRequest(ctx context.Context, requestID, expertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptRequest", ctx, requestID, expertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptRequest indicates an expected call of AcceptRequest.
func (mr *MockRepositoryMockRecorder) AcceptRequest(ctx, requestID, expertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptRequest", reflect.TypeOf((*MockRepository)(nil).AcceptRequest), ctx, requestID, expertID)
}

// CreateRating mocks base method.
func (m *MockRepository) CreateRating(ctx context.Context, rating *domain.ExpertRating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRating", ctx, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRating indicates an expected call of CreateRating.
func (mr *MockRepositoryMockRecorder) CreateRating(ctx, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRating", reflect.TypeOf((*MockRepository)(nil).CreateRating), ctx, rating)
}

// CreateRequest mocks base method.
func (m *MockRepository) CreateRequest(ctx context.Context, req *domain.AssistanceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRequest indicates an expected call of CreateRequest.
func (mr *MockRepositoryMockRecorder) CreateRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockRepository)(nil).CreateRequest), ctx, req)
}

// GetPendingRequests mocks base method.
func (m *MockRepository) GetPendingRequests(ctx context.Context) ([]*domain.AssistanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRequests", ctx)
	ret0, _ := ret[0].([]*domain.AssistanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingRequests indicates an expected call of GetPendingRequests.
func (mr *MockRepositoryMockRecorder) GetPendingRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRequests", reflect.TypeOf((*MockRepository)(nil).GetPendingRequests), ctx)
}

// GetRequestByID mocks base method.
func (m *MockRepository) GetRequestByID(ctx context.Context, requestID uuid.UUID) (*domain.AssistanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestByID", ctx, requestID)
	ret0, _ := ret[0].(*domain.AssistanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestByID indicates an expected call of GetRequestByID.
func (mr *MockRepositoryMockRecorder) GetRequestByID(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestByID", reflect.TypeOf((*MockRepository)(nil).GetRequestByID), ctx, requestID)
}

// ResolveRequest mocks base method.
func (m *MockRepository) ResolveRequest(ctx context.Context, requestID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRequest", ctx, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveRequest indicates an expected call of ResolveRequest.
func (mr *MockRepositoryMockRecorder) ResolveRequest(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRequest", reflect.TypeOf((*MockRepository)(nil).ResolveRequest), ctx, requestID)
}
