// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Tr9QtPHjm1_f05h6MDTYMl53ovgEKEw',
    appId: '1:436822568666:web:fad0f5cce93ebd83743fe3',
    messagingSenderId: '436822568666',
    projectId: 'project-sage-12614',
    authDomain: 'project-sage-12614.firebaseapp.com',
    storageBucket: 'project-sage-12614.firebasestorage.app',
    measurementId: 'G-NY8G8XLYFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjNpuIBodEHzHWRe8ij5d1tU657hEVL8',
    appId: '1:436822568666:android:8ab2bad530ba124c743fe3',
    messagingSenderId: '436822568666',
    projectId: 'project-sage-12614',
    storageBucket: 'project-sage-12614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWntvM1WnNoXnK2L4WJF5tEOEQ6edu2AU',
    appId: '1:436822568666:ios:60f2401e1b65bbff743fe3',
    messagingSenderId: '436822568666',
    projectId: 'project-sage-12614',
    storageBucket: 'project-sage-12614.firebasestorage.app',
    iosBundleId: 'com.projectsage.userApp',
  );
}
