// Code generated by MockGen. DO NOT EDIT.
// Source: clients.go
//
// Generated by this command:
//
//	mockgen -destination=./clients_mock_test.go -package=llm -source=clients.go
//

// Package llm is a generated GoMock package.
package llm

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeminiClient is a mock of GeminiClient interface.
type MockGeminiClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeminiClientMockRecorder
	isgomock struct{}
}

// MockGeminiClientMockRecorder is the mock recorder for MockGeminiClient.
type MockGeminiClientMockRecorder struct {
	mock *MockGeminiClient
}

// NewMockGeminiClient creates a new mock instance.
func NewMockGeminiClient(ctrl *gomock.Controller) *MockGeminiClient {
	mock := &MockGeminiClient{ctrl: ctrl}
	mock.recorder = &MockGeminiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeminiClient) EXPECT() *MockGeminiClientMockRecorder {
	return m.recorder
}

// GenerateContent mocks base method.
func (m *MockGeminiClient) GenerateContent(ctx context.Context, history []*ChatMessage) (*ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContent", ctx, history)
	ret0, _ := ret[0].(*ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateContent indicates an expected call of GenerateContent.
func (mr *MockGeminiClientMockRecorder) GenerateContent(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContent", reflect.TypeOf((*MockGeminiClient)(nil).GenerateContent), ctx, history)
}

// Summarize mocks base method.
func (m *MockGeminiClient) Summarize(ctx context.Context, history []*ChatMessage) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, history)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockGeminiClientMockRecorder) Summarize(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockGeminiClient)(nil).Summarize), ctx, history)
}

// MockChatGatewayClient is a mock of ChatGatewayClient interface.
type MockChatGatewayClient struct {
	ctrl     *gomock.Controller
	recorder *MockChatGatewayClientMockRecorder
	isgomock struct{}
}

// MockChatGatewayClientMockRecorder is the mock recorder for MockChatGatewayClient.
type MockChatGatewayClientMockRecorder struct {
	mock *MockChatGatewayClient
}

// NewMockChatGatewayClient creates a new mock instance.
func NewMockChatGatewayClient(ctrl *gomock.Controller) *MockChatGatewayClient {
	mock := &MockChatGatewayClient{ctrl: ctrl}
	mock.recorder = &MockChatGatewayClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatGatewayClient) EXPECT() *MockChatGatewayClientMockRecorder {
	return m.recorder
}

// GetChatHistory mocks base method.
func (m *MockChatGatewayClient) GetChatHistory(ctx context.Context, twilioSID string) ([]*ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", ctx, twilioSID)
	ret0, _ := ret[0].([]*ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockChatGatewayClientMockRecorder) GetChatHistory(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockChatGatewayClient)(nil).GetChatHistory), ctx, twilioSID)
}
