// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=./service_mock_test.go -package=llm -source=service.go Service
//

// Package llm is a generated GoMock package.
package llm

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SocialChat mocks base method.
func (m *MockService) SocialChat(ctx context.Context, history []*ChatMessage) (*ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SocialChat", ctx, history)
	ret0, _ := ret[0].(*ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SocialChat indicates an expected call of SocialChat.
func (mr *MockServiceMockRecorder) SocialChat(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocialChat", reflect.TypeOf((*MockService)(nil).SocialChat), ctx, history)
}

// SummarizeChatHistory mocks base method.
func (m *MockService) SummarizeChatHistory(ctx context.Context, twilioSID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummarizeChatHistory", ctx, twilioSID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummarizeChatHistory indicates an expected call of SummarizeChatHistory.
func (mr *MockServiceMockRecorder) SummarizeChatHistory(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummarizeChatHistory", reflect.TypeOf((*MockService)(nil).SummarizeChatHistory), ctx, twilioSID)
}
