// Code generated by MockGen. DO NOT EDIT.
// Source: clients.go
//
// Generated by this command:
//
//	mockgen -destination=./clients_mock_test.go -package=chat -source=clients.go
//

// Package chat is a generated GoMock package.
package chat

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTwilioClient is a mock of TwilioClient interface.
type MockTwilioClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwilioClientMockRecorder
	isgomock struct{}
}

// MockTwilioClientMockRecorder is the mock recorder for MockTwilioClient.
type MockTwilioClientMockRecorder struct {
	mock *MockTwilioClient
}

// NewMockTwilioClient creates a new mock instance.
func NewMockTwilioClient(ctrl *gomock.Controller) *MockTwilioClient {
	mock := &MockTwilioClient{ctrl: ctrl}
	mock.recorder = &MockTwilioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwilioClient) EXPECT() *MockTwilioClientMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockTwilioClient) AddParticipant(ctx context.Context, conversationSID, identity string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", ctx, conversationSID, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockTwilioClientMockRecorder) AddParticipant(ctx, conversationSID, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockTwilioClient)(nil).AddParticipant), ctx, conversationSID, identity)
}

// CreateConversation mocks base method.
func (m *MockTwilioClient) CreateConversation(ctx context.Context, friendlyName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, friendlyName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockTwilioClientMockRecorder) CreateConversation(ctx, friendlyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockTwilioClient)(nil).CreateConversation), ctx, friendlyName)
}

// GenerateToken mocks base method.
func (m *MockTwilioClient) GenerateToken(ctx context.Context, identity string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, identity)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockTwilioClientMockRecorder) GenerateToken(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockTwilioClient)(nil).GenerateToken), ctx, identity)
}

// GetConversationHistory mocks base method.
func (m *MockTwilioClient) GetConversationHistory(ctx context.Context, conversationSID string) ([]*Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationHistory", ctx, conversationSID)
	ret0, _ := ret[0].([]*Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationHistory indicates an expected call of GetConversationHistory.
func (mr *MockTwilioClientMockRecorder) GetConversationHistory(ctx, conversationSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationHistory", reflect.TypeOf((*MockTwilioClient)(nil).GetConversationHistory), ctx, conversationSID)
}

// RemoveParticipant mocks base method.
func (m *MockTwilioClient) RemoveParticipant(ctx context.Context, conversationSID, participantSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", ctx, conversationSID, participantSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockTwilioClientMockRecorder) RemoveParticipant(ctx, conversationSID, participantSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockTwilioClient)(nil).RemoveParticipant), ctx, conversationSID, participantSID)
}
