// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=./service_mock_test.go -package=chat -source=service.go Service
//

// Package chat is a generated GoMock package.
package chat

import (
	context "context"
	domain "project-sage/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddExpert mocks base method.
func (m *MockService) AddExpert(ctx context.Context, twilioSID string, expertID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExpert", ctx, twilioSID, expertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExpert indicates an expected call of AddExpert.
func (mr *MockServiceMockRecorder) AddExpert(ctx, twilioSID, expertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExpert", reflect.TypeOf((*MockService)(nil).AddExpert), ctx, twilioSID, expertID)
}

// CreateConversation mocks base method.
func (m *MockService) CreateConversation(ctx context.Context, user *domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConversation", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConversation indicates an expected call of CreateConversation.
func (mr *MockServiceMockRecorder) CreateConversation(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConversation", reflect.TypeOf((*MockService)(nil).CreateConversation), ctx, user)
}

// GenerateExpertToken mocks base method.
func (m *MockService) GenerateExpertToken(ctx context.Context, expert *domain.Expert) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateExpertToken", ctx, expert)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateExpertToken indicates an expected call of GenerateExpertToken.
func (mr *MockServiceMockRecorder) GenerateExpertToken(ctx, expert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateExpertToken", reflect.TypeOf((*MockService)(nil).GenerateExpertToken), ctx, expert)
}

// GenerateUserToken mocks base method.
func (m *MockService) GenerateUserToken(ctx context.Context, user *domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUserToken", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUserToken indicates an expected call of GenerateUserToken.
func (mr *MockServiceMockRecorder) GenerateUserToken(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUserToken", reflect.TypeOf((*MockService)(nil).GenerateUserToken), ctx, user)
}

// GetChatHistory mocks base method.
func (m *MockService) GetChatHistory(ctx context.Context, twilioSID string) ([]*Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", ctx, twilioSID)
	ret0, _ := ret[0].([]*Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockServiceMockRecorder) GetChatHistory(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockService)(nil).GetChatHistory), ctx, twilioSID)
}

// RemoveBot mocks base method.
func (m *MockService) RemoveBot(ctx context.Context, twilioSID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBot", ctx, twilioSID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBot indicates an expected call of RemoveBot.
func (mr *MockServiceMockRecorder) RemoveBot(ctx, twilioSID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBot", reflect.TypeOf((*MockService)(nil).RemoveBot), ctx, twilioSID)
}
